---
- name: install tfc-agent
  hosts: all
  serial: 1
  become: true

  vars:
    TFC_AGENT_NAME: "tfc-agent-example"
    TFC_AGENT_TOKEN : "example"
    TFC_AGENT_VERSION : "latest"

  tasks:

  - name: install common packages
    yum:
      name:
        - unzip
        - vim
        - jq
        - firewalld
      state: present

  - name: enable docker repo
    yum_repository:
      name: docker-ce
      description: Docker CE Repository
      baseurl: "https://download.docker.com/linux/centos/8/$basearch/stable"
      enabled: yes
      gpgcheck: yes
      gpgkey: https://download.docker.com/linux/centos/gpg

  - name: preinstall containerd
    yum:
      name: containerd.io-1.4.4
      update_cache: true
      state: present

  - name: install docker
    yum:
      name: "docker-ce-19.3.15"
      update_cache: true
      state: present
    register: yum_docker_install
    until: yum_docker_install is success
    retries: 3
    delay: 60

  - name: enable docker
    systemd:
      name: docker
      state: started
      enabled: true

  - name: ensure docker group exists
    group:
      name: docker
      state: present

  - name: Add the system user 'tfc-agent'
    user:
      name: tfc-agent
      home: /etc/tfc-agent.d
      shell: /bin/false
      system: yes

  - name: create config directory
    file: 
      path: /etc/tfc-agent.d/
      state: directory
      recurse: yes
      owner: tfc-agent
      group: tfc-agent

  - name: Add user tfc-agent to the 'docker' group
    user:
      name: tfc-agent
      group: docker

  - name: configure env variables
    template:
      src: ./files/tfc-agent.conf.j2
      dest: /etc/tfc-agent.d/tfc-agent.conf

  - name: configure systemd
    template:
      src: ./files/tfc-agent.service.j2
      dest: /etc/systemd/system/tfc-agent.service

  - name: start tfc-agent controller
    systemd:
      name: tfc-agent.service
      state: restarted
      enabled: yes
      daemon_reload: yes